# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [1]:
# Import Numpy
import numpy as np

In [27]:
# Define the 4 matrices as A,B,C,D
A=np.arange(6).reshape(2,3)
B=np.arange(15).reshape(3,5)
C=np.arange(10).reshape(5,2)
D=np.arange(4).reshape(2,2)

In [28]:
# Print the 4 matrices
print(A)
print(B)
print(C)
print(D)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]]


In [29]:
# Find the Dot Product of matrices
AB=np.dot(A,B)
ABC=np.dot(AB,C)
ABCD=np.dot(ABC,D)
print(ABCD)

[[1670 3185]
 [5180 9890]]


# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [30]:

def is_compatible(a, b):
  if a.shape[1]==b.shape[0]:
        res=np.dot(a, b)
        print(res)
        return res
  else:
        print("Dimension Error!!")


In [31]:
AB=is_compatible(A,B)
ABC=is_compatible(AB,C)
ABCD=is_compatible(ABC,D)


[[ 25  28  31  34  37]
 [ 70  82  94 106 118]]
[[ 680  835]
 [2120 2590]]
[[1670 3185]
 [5180 9890]]


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [52]:
r= int(input("Enter number of rounds between 1 and 12: "))
def up_down(rounds):
  guess_comp=np.random.randint(1,13)
  points=0
  while (points<30 and points>-30 and rounds>0):
      guess_play=int(input("Enter guess between 1 and 12: "))
      if (guess_comp<7 and guess_play<7):
        points=points+guess_play
      elif (guess_comp==7 and guess_play==7):
        points=points+14
      elif (guess_comp>7 and guess_play>7):
        points=points+guess_play
      else:
        points=points-guess_play
      rounds=rounds-1
  print("Final points are: ")
  print(points)

if(r<1 or r>12):
  print("Invalid rounds!!")
else:
  up_down(r)

Enter number of rounds between 1 and 12: 3
Enter guess between 1 and 12: 4
Enter guess between 1 and 12: 8
Enter guess between 1 and 12: 7
Final points are: 
-3
