# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [1]:
# Import Numpy
import numpy as np
# Define the 4 matrices as A,B,C,D
A=np.random.randint(20,size=(2,3))
B=np.random.randint(20,size=(3,5))
C=np.random.randint(20,size=(5,2))
D=np.random.randint(20,size=(3,3))
# Print the 4 matrices
print(A,"\nshape is:",A.shape)
print(B,"\nshape is:",B.shape)
print(C,"\nshape is:",C.shape)
print(D,"\nshape is:",D.shape)

[[ 7  8 14]
 [ 7 11 10]] 
shape is: (2, 3)
[[14 17  9 16  5]
 [ 2 17 12 17 10]
 [16  2 15  0  0]] 
shape is: (3, 5)
[[16 18]
 [15 10]
 [ 9 17]
 [11 18]
 [13  8]] 
shape is: (5, 2)
[[11  9  0]
 [ 4 17 18]
 [ 9  9 15]] 
shape is: (3, 3)


In [2]:
# Find the Dot Product of matrices
E = np.dot(A,B)
print("Dot Product of A and B : ", E, "\nshape is:",E.shape)
F = np.dot(E,C)
print("Dot Product of A.B with C : ", F, "\nshape is:",F.shape)
G = np.dot(F,D)
print("Dot Product of A.B.C with D : ", G, "\nshape is:",G.shape)


Dot Product of A and B :  [[338 283 369 248 115]
 [280 326 345 299 145]] 
shape is: (2, 5)
Dot Product of A.B with C :  [[17197 20571]
 [17649 20707]] 
shape is: (2, 2)


ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [3]:
def is_compatible(A, B):
  if A.shape[1]==B.shape[0]:
    x=np.dot(A,B)
    print("\nshape is:",x.shape)
    return x
  else:
    print("Dimension Error!!")

In [4]:
# Find Dot product only if the matrices are compatible
E = is_compatible(A,B)
print("Dot Product of A and B : ", E)
F = is_compatible(E,C)
print("Dot Product of A.B with C : ", F)
G = is_compatible(F,D)
print("Dot Product of A.B.C with D : ", G)


shape is: (2, 5)
Dot Product of A and B :  [[338 283 369 248 115]
 [280 326 345 299 145]]

shape is: (2, 2)
Dot Product of A.B with C :  [[17197 20571]
 [17649 20707]]
Dimension Error!!
Dot Product of A.B.C with D :  None


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [ ]:
def up_down(rounds):
    totalrounds=rounds
    score=0
    while rounds:
        print("Round ", totalrounds-rounds+1)
        num=int(input())
        if num<1 or num>12:
            print("Invalid input\nThe no. should lie between 1 to 12")
        numc=np.random.randint(1,13)
        print("The computer's guess is:",numc)
        if numc<7 and num<7:
            score+=(num+numc)
        elif numc<7 and num>=7:
            score-=(num+numc)
        elif numc>7 and num>7:
            score+=(num+numc)
        elif numc>7 and num<=7:
            score-=(num+numc)
        elif numc==7 and num==7:
            score+=14
        elif numc==7 and num!=7:
            score+=(num+numc)
        
        if score>30:
            print("You win")
            break
        elif score<-30:
            print("You loose")
            break
        rounds-=1
    else:
        print("All rounds are completed")
    print("Your final score is: ",score)

up_down(2)